// Canonical UUIDv7 validation for reviewer submission identifiers.
//
// Submission IDs in this project are generated by the database default
// `uuidv7()` (see migration V002). No legacy submission records with older UUID
// versions exist, so the reviewer endpoint accepts ONLY canonical UUIDv7 and
// rejects everything else (v1-v6, v8, the nil UUID, braces, prefixes/suffixes,
// whitespace, missing hyphens, bad variant bits) before any database lookup.
//
// The pattern is fully anchored, so no surrounding characters or whitespace are
// tolerated. Version nibble must be 7; variant nibble must be 8/9/a/b (RFC 4122
// / RFC 9562 binary variant 10xx).
const UUID_V7_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

// Returns the normalized (lowercase) canonical UUIDv7 string, or null when the
// input is not a canonical UUIDv7. Uppercase input is accepted only after safe
// lowercase normalization; callers MUST use the returned value for the database
// lookup so that no un-normalized string ever reaches the query.
export function normalizeUuidV7(value) {
  if (typeof value !== 'string') return null;
  const lower = value.toLowerCase();
  return UUID_V7_PATTERN.test(lower) ? lower : null;
}

// Convenience predicate for tests and callers that only need a boolean.
export function isCanonicalUuidV7(value) {
  return normalizeUuidV7(value) !== null;
}
